### ISSUE TITLE
Feature request: Support skip push to "latest" in `put`

### ISSUE THREAD

**Issue by SimonXming** [concourse/registry-image-resource#44]
Currently, in registry-resource, it always uses `latest` as the default tag in `put` step. So it pushes the image to the registry using `latest` along with `additional_tags`.

The request is to have `params.tag_file` in `out` config and when a user specifies `tag_file` disable `push latest` in `put` step. So that users have the flexibility to push the image with custom tags and not have `latest` tag by default. 

Or maybe we could provide `params.skip_latest` or something like that.

**Comment by simonxmh** [comment]
+1

**Comment by vito** [comment]
To clarify, it doesn't default to `latest` in the `put` step - it defaults to `latest` in the source definition, and this tag can be changed to anything.

I see your point, but I'm a little iffy on having a skip option here, because it breaks the symmetry of the resource interface - it's meant to point to a canonical tag in `source:` and be able to check it, fetch it, and push to it, adding additional tags along the way. If you're doing `put`s that don't affect the canonical tag, it's asymmetric and slightly broken as `put` will produce versions that wouldn't normally be pulled down by `check`. (Related: https://github.com/concourse/concourse/issues/3463)

Would you be able to just configure a different tag under `source:`?

If not, could you add more info on you use case? What kinds of tags are you pushing that you don't want to have a 'stable' tag?

**Comment by simonxmh** [comment]
I hope I'm not hijacking the thread here. But my use-case for a non-default tag is that I would like to be able to push to the registry image resource using a tagfile much like how we were able to with the docker-image resource. But now when I use the tag-file option in the registry image it gets overwritten by the latest tag that is configured by default in the source tag.

**Comment by vito** [comment]
@simonxmh Not hijacking at all. :)

I'm not sure what you mean by overwritten. Do you mean the tag here?: https://github.com/concourse/registry-image-resource#files-created-by-the-resource

So basically you want to be able to `put` and then have the tag file produced when fetching that version match the tag(s) specified via `additional_tags` instead of the canonical tag?

Can you give an example of a tag you're configuring for these images?

**Comment by simonxmh** [comment]
So the version of the image I want to build is contained in a file within the docker image itself. And I want to use that as the tag_file variable (much like how I was able to with docker-images) when I put the image into a registry. However, now the registry-image resource overwrites that version tag with a mandatory source tag.

**Comment by simonxmh** [comment]
Much like some thing like this
  - put: image
    params:
      import_file: image/image.tar
      tag_file: image/VERSION

**Comment by SimonXming** [comment]
@vito, so in `5.0`,  `put` will insert directly into the resource versions, and it cause some problem. In `6.0`, all version will only come from `check`. 

So for `registry-image-resource`, you would like keep every `put` produce a version detectable for `check`. That why you would like to keep a canonical tag updated. In this case, skip option would be not appropriate.

I'm a little worry about this change, it may impact a lot resource type. We will take a investigation. BTW, I think quite a lot resource type should be implemented as reusable task. But today's default choice seems `resouce-type`, I think because it's easy to treat `resource-type` as plugin 😂. Really looking forward to see `reusable task`  play a more important role in pipeline

**Comment by SimonXming** [comment]
Close since it's not a valid request.
