### ISSUE TITLE
Retry on 429 errors

### ISSUE THREAD

**Issue by vito** [concourse/registry-image-resource#68]
Seems like we're getting this error a lot from Docker Hub all of a sudden:

```
ERRO[0002] failed to get remote image: unrecognized HTTP status: 429 Too Many Requests
```

We should retry with exponential backoff.

**Comment by pivotal-jamie-klassen** [comment]
Just spent about half an hour investigating the case when we see a 429 in a registry-image `get` (when [fetching a layer](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/rc/builds/588#L5db373a0:23)), and we think we traced
https://github.com/concourse/registry-image-resource/blob/master/cmd/in/main.go#L101
-> https://github.com/concourse/registry-image-resource/blob/master/cmd/in/unpack.go#L64
-> https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/descriptor.go#L293,
(assuming we were looking at the correct implementation of `v1.Layer`) which suggests that we should see a [`github.com/google/go-containerregistry/pkg/v1/remote/transport.Error`](https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/transport/error.go#L25-L33) with a `.StatusCode` field of `429`. We're going to try to create a reproducible for the resource checking path, since that is probably a faster feedback signal (assuming that checking does something lightweight like querying for some JSON or downloading a manifest, rather than an entire layer blob which sounds kinda slow).

**Comment by pivotal-jamie-klassen** [comment]
looks like it's the same story for checking, we're definitely passing into [this block](https://github.com/concourse/registry-image-resource/blob/master/cmd/check/main.go#L127) and `.StatusCode` is 429.
