### ISSUE TITLE
Question about the plan for tagging built images

### ISSUE THREAD

**Issue by pn-santos** [concourse/registry-image-resource#7]
_Disclaimer: Not sure if this is the right place to post this, or if it's "too soon" in the development for asking (seeing this is still "beta"). Apologies if it is._

I was wondering what the vision/plan is for tagging images. I know put is still very early stages but this resource as it stands, requires tags to be specified "statically" (in the pipeline config). However I think it's a frequent use case to tag built images with runtime generated values (like auto-incremented build nr, or git rev, etc.). 

I've been experimenting with this resource (and the [builder task](https://github.com/concourse/builder/) - they work well and much faster than the docker-image resource btw :+1:) and I've been pondering whether it would be useful to add the ability to read tags from a file when specifying a put (for example). But not sure if it fits in the plans for this resource.

From a design perspective it seems to go against specifying the tag in the source definition, since that implies the resource is tracking a specific tag, so for symmetry the put should update the tag...

**Comment by vito** [comment]
Good question (sorry for the delay, end-of-year vacations took me away for a while)! Tags were a major source of confusion in the Docker Image resource and the interface around them was constantly in flux. It was scary enough that I haven't added support for it yet, but if we can all agree on the behavior I'd be happy to merge a PR for it.

And thanks for the feedback re: the `builder` task, glad to hear it's working out well! :+1: 

For now, I think it still makes sense to have a tag in `source` since there needs to be some way of specifying where the versions are coming from. This may change in the future with concourse/rfcs#1 (more on that later).

I think we could pretty much replicate the `additional_tags` feature from the Docker Image resource, and ignore the other tag-related params. It would push the tags read from the specified file (whitespace/linebreak-separated), in addition to the tag specified by `source` (or `latest` if not specified, so its default is consistent with `get` and `check`).

There's usually a central tag to update with `put`, and usually people want to add *additional* tags, e.g. push to `latest` or `dev` while also tagging it with specific versions. Something like `latest`, `1.2.3`, `1.2`, `1`.

The only gotcha I can think of is when publishing patches of older minor releases. If you've already shipped v1.2.0 and you want to publish a patch version like v1.1.9, you would only want to push two tags: `1.1.9` and `1.1`. You wouldn't want to push to `latest` because that should be pointing at v1.2.x. So you would have to use a resource that has `1.1` as its pre-configured tag, and specify only `1.1.9` via `additional_tags`. This kind of makes sense to me anyway, though; it'd be confusing to have a resource tracking `latest` but then only push digests that `latest` will never point to.

It may be worth thinking ahead to how this resource will work once spaces (concourse/concourse#1707) and the v2 resource interface (concourse/rfcs#1) is finished. The current plan is for each tag to be its own space. We would remove `tag` from the source config, because the resource would now be detecting all of them. (In its place there may be some configuration to filter the detected spaces, if desired.) At this point I think it would make total sense for `put` to push to an entirely dynamic set of tags, because now `put` can push to many spaces, and there won't be any broken symmetry because there's no longer a canonical tag that the resource is tracking. At this point the only change may be to just rename `additional_tags` to `tags`.

How's all that sound? :slightly_smiling_face:

**Comment by pn-santos** [comment]
> Good question (sorry for the delay, end-of-year vacations took me away for a while)

Ditto for this reply :slightly_smiling_face: 

> _For now, I think it still makes sense to have a tag in source since there needs to be some way of specifying where the versions are coming from_

I agree :100:. To me this is the equivalent of the `branch` param in the git resource so it makes sense to define it under `source`.

> _I think we could pretty much replicate the `additional_tags` feature from the Docker Image resource, and ignore the other tag-related params. It would push the tags read from the specified file (whitespace/linebreak-separated), in addition to the tag specified by `source` (or `latest` if not specified, so its default is consistent with `get` and `check`)._

This sounds good to me and I think would be sufficient to solve the majority of dynamic tagging needs out there.

> _The only gotcha I can think of is when publishing patches of older minor releases. If you've already shipped v1.2.0 and you want to publish a patch version like v1.1.9, you would only want to push two tags: `1.1.9` and `1.1`. You wouldn't want to push to `latest` because that should be pointing at v1.2.x. So you would have to use a resource that has `1.1` as its pre-configured tag, and specify only `1.1.9` via `additional_tags`_

I think this is ok. A `tag` is essentially a "branch" of an image repo. So I think it makes sense to have to define a resource to track the support branch/tag (i.e. `1.1`). 

As least in a _pre-spaces_ scenario that's usually the way I do it for git resources. Either the pipeline definition in the support branch gets its resources updated to track the support branch (and a new pipeline is created from it) or the appropriate resources and jobs get added to the "master" pipeline for the branch in question. So it would be consistent to also do that for all registry-image resources imo.

The difference to the current docker-image resource would be that for any one of the N tags a `put` adds/updates, one of them is specified in the corresponding resource source (which actually seems more consistent than what the current docker-image resource does, where a `put` may not even update the tag the corresponding resource is tracking, meaning you can `put` and not generate a new version of the resource in question). 

> At this point I think it would make total sense for put to push to an entirely dynamic set of tags, because now put can push to many spaces, and there won't be any broken symmetry because there's no longer a canonical tag that the resource is tracking. At this point the only change may be to just rename additional_tags to tags.
>
> How's all that sound? :slightly_smiling_face:_

Sounds like spaces will be awesome! ^_^
