### ISSUE TITLE
Support `skip_download`?

### ISSUE THREAD

**Issue by amnk** [concourse/registry-image-resource#92]
Currently, when using `skip_download`, this resource produces ```ERRO[0000] invalid payload: json: unknown field "skip_download" ```

Will it be possible to add that?

**Comment by absconcept** [comment]
I hope we can resolve this soon

**Comment by FlorianSW** [comment]
As a user of both, the registry-image and the docker-image, resources, and given the following key difference of registry-image to docker-image:
```
A goal of this resource is to stay as focused and simple as possible. The Docker Image resource grew way too large and complicated. There are simply too many ways to build and publish Docker images. It will be easier to support many smaller resources + tasks rather than one huge interface.
```
I would be super interested in the use case of such a flag :D You just said, that it does not exist, which is true, but for a real consideration, if this resource should've such a functionality, I think the actual use case (so, what you want to achieve) would be very very helpful :)

**Comment by v-yarotsky** [comment]
I have a simple pipeline:
- Grab new version of a repo's master branch
- Build the docker image
- Push the docker image 
- Deploy the image to k8s

Downloading the docker image within the pipeline is of no use to me. While uploading takes seconds because of the docker registry layer cache, downloading takes a minute or more sometimes, slowing my team's CI cycle unnecessarily.

I have dozens of these pipelines. Having a flag `skip_download` would speed all of them up considerably, which I know would be greatly appreciated by my teammates.

**Comment by FlorianSW** [comment]
Alright, that makes sense, thanks for providing your use case :)

**Comment by YoussB** [comment]
#181 merged, closing.
