### ISSUE TITLE
Allow ECR access without aws_access_key_id and aws_secret_access_key

### ISSUE THREAD

**Issue by william-tran** [concourse/registry-image-resource#94]
I've been trying out the ECR features that were just added, thanks! Our workers already have an assumed role, so they don't need to auth using an access key. PR coming shortly

**Comment by analytically** [comment]
@vito

**Comment by vito** [comment]
Per https://github.com/concourse/registry-image-resource/pull/98#issuecomment-603831712, this is not a change we can make to the resource type.

The latest activity on this problem area is here: https://github.com/concourse/concourse/issues/3023#issuecomment-641549693 - we need Prototypes implemented, and Prototype-based var sources in order to provide worker role-based auth without breaking the resource model. The Prototypes RFC is expected to be merged in 2 weeks - it has a newly added section on [Encryption](https://github.com/vito/rfcs/blob/prototypes/037-prototypes/proposal.md#encryption) which was the missing piece that should them safe to use for credential management.
